
    create table order_item (
        quantity integer not null check (quantity>=1),
        total_price numeric(10,2) not null,
        unit_price numeric(10,2) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_code varchar(50),
        product_image varchar(255),
        product_name varchar(255) not null,
        primary key (id)
    );

    create table orders (
        discount numeric(10,2),
        shipping_cost numeric(10,2),
        shipping_state varchar(2) not null,
        subtotal numeric(10,2),
        total numeric(10,2) not null,
        cancelled_at timestamp(6),
        created_at timestamp(6) not null,
        delivered_at timestamp(6),
        id bigint generated by default as identity,
        moment timestamp(6) with time zone,
        paid_at timestamp(6),
        shipped_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        shipping_zip_code varchar(10) not null,
        customer_phone varchar(20),
        payment_status varchar(20) check (payment_status in ('PENDING','PROCESSING','PAID','FAILED','CANCELLED','REFUNDED')),
        status varchar(20) not null check (status in ('PENDING','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED')),
        order_number varchar(50) not null unique,
        payment_method varchar(50),
        shipping_city varchar(100) not null,
        tracking_code varchar(100),
        cancellation_reason TEXT,
        customer_email varchar(255),
        customer_name varchar(255),
        notes TEXT,
        shipping_address TEXT not null,
        shipping_complement varchar(255),
        primary key (id)
    );

    create table password_reset_tokens (
        expiry_date timestamp(6),
        id bigint generated by default as identity,
        integrador_id bigint not null unique,
        token varchar(255),
        primary key (id)
    );

    create table payment (
        amount numeric(10,2) not null,
        card_last_digits varchar(4),
        installment_amount numeric(10,2),
        installments integer check (installments>=1),
        created_at timestamp(6) not null,
        expires_at timestamp(6),
        id bigint generated by default as identity,
        order_id bigint not null unique,
        paid_at timestamp(6),
        updated_at timestamp(6),
        payment_method varchar(20) not null check (payment_method in ('CREDIT_CARD','DEBIT_CARD','PIX','BOLETO')),
        status varchar(20) not null check (status in ('PENDING','PROCESSING','PAID','FAILED','CANCELLED','REFUNDED')),
        card_brand varchar(50),
        boleto_barcode varchar(100),
        transaction_id varchar(100) not null unique,
        boleto_url TEXT,
        failure_reason TEXT,
        pix_code TEXT,
        pix_qr_code TEXT,
        processor_response TEXT,
        primary key (id)
    );

    create table product_images (
        product_id bigint not null,
        image_url varchar(255)
    );

    create table products (
        ativo boolean not null,
        avaliacoes integer check ((avaliacoes<=5) and (avaliacoes>=0)),
        em_destaque boolean not null,
        estoque integer not null check (estoque>=0),
        preco numeric(10,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        codigo_categoria varchar(50) not null unique,
        disponibilidade varchar(50) not null,
        categoria varchar(100) not null,
        marca varchar(100),
        subcategoria varchar(100),
        tipo varchar(100),
        descricao TEXT not null,
        imagem varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table tb_integrador (
        is_mei boolean,
        role smallint check (role between 0 and 1),
        id bigint generated by default as identity,
        cnpj varchar(18) not null unique,
        address varchar(255),
        address_complement varchar(255),
        address_number varchar(255),
        city varchar(255),
        company_name varchar(255),
        email varchar(255) not null unique,
        neighborhood varchar(255),
        password varchar(255) not null,
        phone varchar(255),
        postal_code varchar(255),
        state varchar(255),
        state_registration varchar(255),
        trade_name varchar(255),
        whatsapp varchar(255),
        primary key (id)
    );

    alter table if exists order_item 
       add constraint FKt4dc2r9nbvbujrljv3e23iibt 
       foreign key (order_id) 
       references orders;

    alter table if exists order_item 
       add constraint FKc5uhmwioq5kscilyuchp4w49o 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKr3c8msfgxho9xqqnkd822asi5 
       foreign key (user_id) 
       references tb_integrador;

    alter table if exists password_reset_tokens 
       add constraint FKbhk3wgnq8o7jibnxupa6cdua7 
       foreign key (integrador_id) 
       references tb_integrador;

    alter table if exists payment 
       add constraint FKlouu98csyullos9k25tbpk4va 
       foreign key (order_id) 
       references orders;

    alter table if exists product_images 
       add constraint FKqnq71xsohugpqwf3c9gxmsuy 
       foreign key (product_id) 
       references products;
